#!/bin/sh
# Configure per-user Firefox VA-API integration for msm_drm.
#
# Usage: configure-firefox-vaapi.sh [--verify|--uninstall]
# Environment: DMD_DRIVER_DIR overrides automatic driver-directory selection.

set -u

BEGIN_MARKER='// BEGIN DMD MSM VA-API MANAGED PREFS'
END_MARKER='// END DMD MSM VA-API MANAGED PREFS'
FIREFOX_HOME="$HOME/.mozilla/firefox"
PROFILES_INI="$FIREFOX_HOME/profiles.ini"
LOCAL_BIN="$HOME/.local/bin"
WRAPPER="$LOCAL_BIN/firefox-msm-vaapi"
APPLICATIONS="$HOME/.local/share/applications"
DESKTOP="$APPLICATIONS/firefox.desktop"
DESKTOP_BACKUP="$APPLICATIONS/firefox.desktop.dsh-msm-vaapi.backup"

say() { printf '%s\n' "$*"; }
err() { printf '%s\n' "error: $*" >&2; }

usage() {
    cat <<'EOF'
Usage: configure-firefox-vaapi.sh [--verify|--uninstall]

Install is the default. DMD_DRIVER_DIR can select the directory containing
msm_drm_drv_video.so; otherwise the highest-versioned
~/Documents/DSHWK/release-v* directory that contains the driver is used,
falling back to /usr/lib/aarch64-linux-gnu/dri.
EOF
}

firefox_running() {
    command -v pgrep >/dev/null 2>&1 || return 1
    pgrep -x firefox >/dev/null 2>&1 || pgrep -x firefox-esr >/dev/null 2>&1
}

select_driver_dir() {
    if [ -n "${DMD_DRIVER_DIR:-}" ]; then
        DRIVER_DIR=$DMD_DRIVER_DIR
    else
        # 挑版本号最大的 release-v* 目录，不要硬编码某个版本 —— 否则升级后
        # 脚本会继续指向旧驱动。sort -V 按版本序排，取最后一个。
        DRIVER_DIR=''
        for d in $(ls -d "$HOME"/Documents/DSHWK/release-v* 2>/dev/null | sort -V); do
            [ -f "$d/msm_drm_drv_video.so" ] && DRIVER_DIR=$d
        done
        [ -n "$DRIVER_DIR" ] || DRIVER_DIR=/usr/lib/aarch64-linux-gnu/dri
    fi

    if [ ! -f "$DRIVER_DIR/msm_drm_drv_video.so" ]; then
        err "msm_drm_drv_video.so not found in $DRIVER_DIR"
        return 1
    fi
    return 0
}

# Print each profile directory. profiles.ini paths can be absolute or relative
# to ~/.mozilla/firefox and may contain spaces, so do not split the output.
profile_dirs() {
    [ -f "$PROFILES_INI" ] || return 1
    awk -v root="$FIREFOX_HOME" '
        function emit() {
            if (in_profile && path != "") {
                if (relative == "0" || path ~ /^\//) print path
                else print root "/" path
            }
        }
        /^\[/ { emit(); in_profile = ($0 ~ /^\[Profile[^]]*\]$/); path=""; relative="1"; next }
        in_profile && /^Path=/ { path=substr($0, 6); next }
        in_profile && /^IsRelative=/ { relative=substr($0, 12); next }
        END { emit() }
    ' "$PROFILES_INI"
}

rewrite_user_js() {
    userjs=$1
    tmp="$userjs.dsh-vaapi.$$"
    mkdir -p "$(dirname "$userjs")" || return 1
    [ -f "$userjs" ] || : > "$userjs" || return 1

    # Delete precisely our prior managed range, preserving all user-owned lines.
    awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
        $0 == begin { skipping=1; next }
        skipping && $0 == end { skipping=0; next }
        !skipping { print }
    ' "$userjs" > "$tmp" || { rm -f "$tmp"; return 1; }
    cat >> "$tmp" <<EOF
$BEGIN_MARKER
// Managed by configure-firefox-vaapi.sh. Do not edit inside this block.
user_pref("media.hardware-video-decoding.enabled", true);
user_pref("media.ffmpeg.vaapi.enabled", true);
user_pref("media.hevc.enabled", true);
user_pref("media.ffmpeg.vaapi.force-surface-zero-copy", 2);
$END_MARKER
EOF
    mv "$tmp" "$userjs"
}

remove_user_js_block() {
    userjs=$1
    [ -f "$userjs" ] || return 0
    tmp="$userjs.dsh-vaapi.$$"
    awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
        $0 == begin { skipping=1; next }
        skipping && $0 == end { skipping=0; next }
        !skipping { print }
    ' "$userjs" > "$tmp" || { rm -f "$tmp"; return 1; }
    mv "$tmp" "$userjs"
}

write_wrapper() {
    mkdir -p "$LOCAL_BIN" || return 1
    cat > "$WRAPPER" <<EOF
#!/bin/sh
# Generated by configure-firefox-vaapi.sh.
export MOZ_DISABLE_RDD_SANDBOX=1
export LIBVA_DRIVER_NAME=msm_drm
export LIBVA_DRIVERS_PATH='$DRIVER_DIR'
exec firefox "\$@"
EOF
    chmod 755 "$WRAPPER"
}

write_desktop() {
    mkdir -p "$APPLICATIONS" || return 1
    # Preserve the user's launcher exactly once. A re-install must not back up
    # our generated launcher as though it were user data.
    if [ -f "$DESKTOP" ] && [ ! -f "$DESKTOP_BACKUP" ]; then
        cp "$DESKTOP" "$DESKTOP_BACKUP" || return 1
    fi
    cat > "$DESKTOP" <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Firefox
Comment=Web Browser (msm VA-API)
Exec=$WRAPPER %u
Terminal=false
Icon=firefox
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/x-xpinstall;application/pdf;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
EOF
}

install() {
    if firefox_running; then
        err "Firefox is running; close Firefox before changing its profiles"
        return 1
    fi
    select_driver_dir || return 1
    if [ ! -f "$PROFILES_INI" ]; then
        err "profiles.ini not found: $PROFILES_INI"
        return 1
    fi

    if ! profile_dirs | grep -q .; then
        err "no [Profile*] Path entries found in $PROFILES_INI"
        return 1
    fi
    # ⚠️ 不要写成 `profile_dirs | while ...`：管道让循环跑在子 shell 里，
    # 循环内的 exit/return 只终止子 shell，写失败会被静默吞掉并照常报
    # "installed"（实测过）。改用重定向喂 while，循环就在当前 shell 里。
    profile_list=$(profile_dirs) || return 1
    failed=0
    while IFS= read -r profile; do
        [ -n "$profile" ] || continue
        if rewrite_user_js "$profile/user.js"; then
            say "configured: $profile/user.js"
        else
            err "failed to write $profile/user.js"
            failed=1
        fi
    done <<EOF
$profile_list
EOF
    [ "$failed" -eq 0 ] || return 1
    write_wrapper || return 1
    write_desktop || return 1
    say "installed Firefox VA-API integration (driver: $DRIVER_DIR)"
}

uninstall() {
    if firefox_running; then
        err "Firefox is running; close Firefox before changing its profiles"
        return 1
    fi
    failed=0
    if [ -f "$PROFILES_INI" ]; then
        # 同 install()：不用管道，避免子 shell 吞掉失败。
        profile_list=$(profile_dirs) || profile_list=''
        while IFS= read -r profile; do
            [ -n "$profile" ] || continue
            if remove_user_js_block "$profile/user.js"; then
                say "removed managed prefs: $profile/user.js"
            else
                err "failed to rewrite $profile/user.js"
                failed=1
            fi
        done <<EOF
$profile_list
EOF
    fi
    rm -f "$WRAPPER"
    if [ -f "$DESKTOP_BACKUP" ]; then
        mv "$DESKTOP_BACKUP" "$DESKTOP"
        say "restored: $DESKTOP"
    else
        rm -f "$DESKTOP"
        say "removed: $DESKTOP"
    fi
    [ "$failed" -eq 0 ] || return 1
    say "uninstalled Firefox VA-API integration"
}

report() { printf '%-28s %s\n' "$1" "$2"; }
read_one_line() { [ -r "$1" ] && sed -n '1p' "$1" || printf 'unavailable'; }

verify_devfreq() {
    found=0
    for d in /sys/class/devfreq/*; do
        [ -d "$d" ] || continue
        name=$(read_one_line "$d/name")
        case "$name" in
            *mvs0*|*mvs1*|*mvsc*|*venus*|*Venus*)
                found=1
                gov=$(read_one_line "$d/governor")
                cur=$(read_one_line "$d/cur_freq")
                report "Venus $name" "governor=$gov cur_freq=$cur"
                ;;
            *bus*|*Bus*|*bw*|*BW*)
                found=1
                cur=$(read_one_line "$d/cur_freq")
                report "bus frequency $name" "$cur"
                ;;
        esac
    done
    [ "$found" -eq 1 ] || report "Venus/bus devfreq" "unavailable under /sys/class/devfreq"
}

verify() {
    if select_driver_dir; then
        report "driver" "OK: $DRIVER_DIR/msm_drm_drv_video.so"
    else
        report "driver" "MISSING (set DMD_DRIVER_DIR if needed)"
    fi
    [ -x "$WRAPPER" ] && report "launcher" "OK: $WRAPPER" || report "launcher" "MISSING: $WRAPPER"
    [ -f "$DESKTOP" ] && report "desktop override" "OK: $DESKTOP" || report "desktop override" "MISSING: $DESKTOP"

    # 找真正在解码的进程。⚠️ 不要用 `pgrep -f 'rdd$'`：RDD 的命令行末尾是
    # -sandboxReporter 之类的参数，不是 "rdd"，实测匹配不到任何进程并误报
    # "not running"。可靠判据是"加载了本驱动"或"持有 /dev/video32"。
    rdds=''
    if command -v pgrep >/dev/null 2>&1; then
        for pid in $(pgrep -f '/firefox' 2>/dev/null || :); do
            [ -r "/proc/$pid/maps" ] || continue
            if grep -q 'msm_drm_drv_video\.so' "/proc/$pid/maps" 2>/dev/null ||
               ls -l "/proc/$pid/fd" 2>/dev/null | grep -q 'video32'; then
                rdds="$rdds $pid"
            fi
        done
    fi
    if [ -n "$rdds" ]; then
        for pid in $rdds; do
            envs=$(tr '\000' '\n' < "/proc/$pid/environ" 2>/dev/null | sed -n '/^MOZ_DISABLE_RDD_SANDBOX=/p;/^LIBVA_DRIVER_NAME=/p;/^LIBVA_DRIVERS_PATH=/p')
            maps=$(grep -c 'msm_drm_drv_video\.so' "/proc/$pid/maps" 2>/dev/null || :)
            fds=$(ls -l "/proc/$pid/fd" 2>/dev/null | grep -c 'video32' || :)
            report "decoder $pid environment" "${envs:-missing}"
            report "decoder $pid driver maps" "$maps"
            report "decoder $pid /dev/video32 fds" "$fds"
        done
    else
        report "decoder process" "none loaded this driver (play a video first)"
    fi

    if [ -e /dev/video32 ]; then
        report "/dev/video32" "present (readable=$([ -r /dev/video32 ] && printf yes || printf no), writable=$([ -w /dev/video32 ] && printf yes || printf no))"
    else
        report "/dev/video32" "missing"
    fi
    verify_devfreq
}

case "${1:-}" in
    '') install ;;
    --verify) verify ;;
    --uninstall) uninstall ;;
    -h|--help) usage ;;
    *) err "unknown option: $1"; usage >&2; exit 2 ;;
esac
